spring:
  mvc:
    pathmatch:
      matching-strategy: "ant-path-matcher"
  datasource:
    url: jdbc:postgresql://localhost:5432/dbrequestserver?prepareThreshold=0
    username: dbrequestserver
    password: dbrequestserver
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    encoding: UTF-8
    sql-migration-prefix: migration
    schemas: public
    locations: classpath:db/migration/postgres
    validate-on-migrate: true

  rabbitmq:
    publisher-returns: true
    publisher-confirm-type: correlated

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/test
          jwk-set-uri: http://localhost:8080/auth/realms/test/protocol/openid-connect/certs

  cloud:
    stream:
      bindings:
        output-request:
          destination: request-processor.output
        input-in-0:
          group: request-processor.input
          destination: request-processor
          consumer:
            batch-mode: true
      rabbit:
        bindings:
          input-in-0:
            consumer:
              auto-bind-dlq: true
              batch-size: 10
              declare-exchange: true
              exchange-type: direct
              binding-routing-key: some-input-routing-key
          output-request:
            producer:
              useConfirmHeader: true
              declare-exchange: true
              exchange-type: direct
              routingKeyExpression: some-output-routing-key
      binders:
        platformRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

spring-doc:
  swagger-ui:
    path: /request-server/swagger-ui.html
  api-docs:
    path: /request-server/api-docs

management:
  server:
    base-path: /manage
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: [ 'health', 'info', 'env', 'metrics', 'loggers' ]
